version: "1"

services:
  postgres:
    image: postgres:14.5-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tcc
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
